//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public int ExchangeID { get; set; }
        public Nullable<int> StuID { get; set; }
        public Nullable<int> OldFloorID { get; set; }
        public Nullable<int> OldDormID { get; set; }
        public Nullable<int> NewFloorID { get; set; }
        public Nullable<int> NewDormID { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Dorm Dorm { get; set; }
        public virtual Dorm Dorm1 { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Floor Floor1 { get; set; }
    }
}
