//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCHomeEntitiesDB : DbContext
    {
        public GCHomeEntitiesDB()
            : base("name=GCHomeEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Dorm> Dorm { get; set; }
        public virtual DbSet<Floor> Floor { get; set; }
        public virtual DbSet<Moveinto> Moveinto { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
    }
}
