//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moveinto
    {
        public int MoveintoID { get; set; }
        public Nullable<int> StuID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> DormID { get; set; }
        public Nullable<System.DateTime> MoveintoTime { get; set; }
        public string MoveintoPeople { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        public virtual Dorm Dorm { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Student Student { get; set; }
    }
}
