//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StuID { get; set; }
        public string StuNumber { get; set; }
        public string StuName { get; set; }
        public string StuCount { get; set; }
        public string StuPwd { get; set; }
        public Nullable<int> StuSex { get; set; }
        public Nullable<int> StuAge { get; set; }
        public Nullable<int> OccupancyStatus { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
